# These are supported funding model platforms

github: [sercanboyraz]
patreon: sercanboyraz
open_collective: e-commerce
ko_fi: sercanboyraz
otechie: sercanboyraz
custom: https://tr.linkedin.com/in/sercan-boyraz-a40429b7
